### PR TITLE
CI: GitHub Actions: add build and release pipelines

### PR DESCRIPTION
**Pull request by aklomp**
Hey there, thanks for this project. I came across it a while ago on a Hacker News thread and I liked it because of its simplicity. I'm also working on my CV at the moment and decided to use your project as a starting point.

I want to show my appreciation with this pull request that sets up a few GitHub Actions:

- On each push to the repo, the source is automatically compiled to a PDF, and the PDF is retained for one day. [Example of a successful run with a ~downloadable~ (Edit: only visible for the author) PDF.](https://github.com/aklomp/1player-resume/actions/runs/2552171250)(I want to avoid installing LaTeX on my machine if at all possible. Better to compile it reproducibly in the cloud.)
- Whenever a tag is pushed in the form of `v<something>`, for example `v1.0`, then a release package `resume-1.0` is automatically created. This release package is persistent and public, so the PDF will be archived there for download.

If you look at the [my fork](https://github.com/aklomp/1player-resume), you'll see that I released a `v0.0` as a test. It's your resume of course, so please excuse me for "releasing" on your behalf, it's just to demonstrate the effect.

### CODE REVIEW

**Comment by 1player** [comment]
Thanks, I haven't had time to look at this yet because I've been swamped with work, but I wanted to say I appreciate it! Happy to know my crappy LaTeX skills have been useful to someone.

I haven't used Github Actions before so this is a good chance to learn. I'll try to do that this weekend.

**Comment by aklomp** [comment]
No rush, this PR isn't going anywhere, so process it at your leisure. It's not blocking me.

**Comment by 1player** [comment]
Thanks for having taken the time for this PR, Alfred, I appreciate it. 

Sadly I don't think I can make much use of it because I'm pretty crap with LaTeX myself, so I have to have it installed on my machine to make sure every change I make looks OK before committing and pushing. I don't think I would benefit from having Github rendering the source on its servers since I already do the rendering on my machine first.

Certainly, I've learned a lot about how Actions works (I haven't used them very much before) from this PR, and feel free to use this repo for inspiration for your resume.

BTW I've been using `lualatex` on my PC, and you instead use `xelatex`. I still don't know the difference between the two, I've heard the former is more active but there might be more slight changes between the two. No idea.

**Comment by aklomp** [comment]
No worries at all, I wrote this code mainly for my own benefit because I wanted to avoid installing LaTeX on my machine unless absolutely necessary. (It's a huge system that drops tools and binaries everywhere.) I used your repo as a base because it was a convenient starting point, but I've since adapted the code to my own CV repo, which I keep private for now. So the effort isn't wasted or anything. I'm glad you appreciate my contribution, feel free to close this PR.

I used `xelatex` in the build only because it was the first LaTeX dialect I could find that would compile the source, not for some deeper reason.

**Pull request closed without merging**
